//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angular_webapi_example.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string techno { get; set; }
        public string message { get; set; }
    }
}
